---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Create mirror root directory
  file:
    path: /srv/mirror
    state: directory
    mode: 0755

- name: Setup sites-enabled/mirror
  register: nginxconf
  template:
    src: mirror.conf.j2
    dest: /etc/nginx/sites-enabled/mirror

- name: Remove debian-packaged homepage
  file:
    state: absent
    path: /var/www/html/index.nginx-debian.html

- name: Install mirror homepage html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Install mirror homepage css
  copy:
    src: style.css
    dest: /var/www/html/style.css

- name: Remove default nginx site
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default

- name: Restart nginx
  when: nginxconf.changed
  service:
    name: nginx
    state: reloaded

