---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Remove default debian vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload-nginx

- name: Create mirror root directory
  file:
    path: /srv/mirror
    state: directory
    mode: 0755

- name: Template http vhost
  copy:
    src: mirror.conf
    dest: /etc/nginx/sites-available/mirror

- name: Symlink http vhost
  file:
    src: /etc/nginx/sites-available/mirror
    dest: /etc/nginx/sites-enabled/mirror
    state: link
  notify: reload-nginx

- name: Start nginx
  meta: flush_handlers

- name: Remove debian-packaged homepage
  file:
    state: absent
    path: /var/www/html/index.nginx-debian.html

