---
- name: Install manjaro sync script
  copy:
    src: manjaroreposync
    dest: /usr/local/bin/mirror-manjaro
    mode: 0755

- name: Create manjaro sync dir
  file:
    path: /srv/mirror/manjaro
    state: directory
    mode: 0755

- name: Add mirror cron entry
  cron:
    name: "sync manjaro mirrors"
    hour: "*/4"
    job: /usr/local/bin/mirror-manjaro

- name: Add xiph user
  user:
    name: xiph

- name: Create xiph sync dir
  file:
    path: /srv/mirror/xiph
    state: directory
    mode: 0755
    owner: xiph

- name: Set up rrsync script
  copy:
    src: /usr/share/doc/rsync/scripts/rrsync
    dest: /usr/local/bin/rrsync
    mode: 0755
    remote_src: yes

- name: Set up xiph ssh pubkey
  authorized_key:
    user: xiph
    state: present
    exclusive: True
    key: '{{ item }}'
    key_options: 'restrict,command="rrsync /srv/mirror/xiph"'
  with_file:
    - xiph.pub

