---
mirrors:
- name: armbian/apt
  source: rsync://rsync.armbian.com/apt
- name: armbian/dl
  source: rsync://rsync.armbian.com/dl
- name: blackarch
  source: rsync://blackarch.org/blackarch/
- name: draugeros/apt
  source: rsync://apt.draugeros.org/aptsync
- name: draugeros/download
  source: rsync://apt.draugeros.org/downloadsync
- name: garuda/repos
  source: builds.garudalinux.org::chaotic
- name: garuda/iso
  source: builds.garudalinux.org::iso
- name: ipfire
  source: rsync.ipfire.org::full
- name: manjaro
  source: rsync://repo.manjaro.org/repos/
- name: serpentos/downloads
  source: rsync://download.serpentos.com/downloads
- name: serpentos/repository
  source: rsync://download.serpentos.com/repository
- name: ubuntudde
  source: rsync://repo.ubuntudde.com/ubuntudde/
- name: xiph
  source: rsync://ftp.osuosl.org/xiph/releases
