---
- name: Run package upgrades
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    upgrade: safe

- name: Install basic tools
  apt:
    pkg:
    - unattended-upgrades
    - htop
    - vim
    - rsync
    - certbot
    - goaccess

- name: Disable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: PasswordAuthentication no
  notify: restart-ssh

